// Copies the circle-flags package's plain ISO-alpha-2 SVGs (skips the
// hyphenated regional variants, e.g. "af-emirate.svg") into public/flags so
// Vite serves them as static assets -- self-hosted, no CDN. Not committed to
// git (see .gitignore): it's fully reproducible from the npm dependency, so
// it's regenerated by predev/prebuild instead, same idea as node_modules.
import { readdirSync, mkdirSync, copyFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "..", "node_modules", "circle-flags", "flags");
const dest = join(here, "..", "public", "flags");

mkdirSync(dest, { recursive: true });
const files = readdirSync(src).filter((f) => /^[a-z]{2}\.svg$/.test(f));
for (const f of files) copyFileSync(join(src, f), join(dest, f));
console.log(`sync-flags: copied ${files.length} flag icons to public/flags/`);
